name: gallery2
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_storage:
  cloud_firestore:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
